FROM rust:1.73-slim-buster

RUN apt-get --yes update && apt-get --yes install git pkg-config libssl-dev
RUN cargo install trunk --version 0.16.0
RUN rustup target add wasm32-unknown-unknown
RUN rustup component add rustfmt
RUN rustup component add clippy-preview