FROM rust:1.70-slim-bullseye

RUN apt-get --yes update && apt-get --yes install git pkg-config libssl-dev nginx && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN cargo install trunk --version 0.16.0
RUN rustup target add wasm32-unknown-unknown
RUN rustup component add rustfmt
RUN rustup component add clippy-preview